resources:
- allow-argocd-to-manage.yaml
- argocd-permissions.yaml
- https://github.com/redhat-appstudio/application-service/config/default?ref=fa1b322bcc71753e1cd7a566a01fdcf6d85eeacd
- .tekton/


apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

images:
- name: quay.io/redhat-appstudio/application-service
  newName: quay.io/redhat-appstudio/application-service
  newTag: fa1b322bcc71753e1cd7a566a01fdcf6d85eeacd

configMapGenerator:
- literals:
  - GITHUB_ORG=""
  name: github-config
  behavior: replace

namespace: application-service

patches:
  - ./manager_resources_patch.yaml
