resources:
- allow-argocd-to-manage.yaml
- argocd-permissions.yaml
- https://github.com/redhat-appstudio/release-service/config/default?ref=e9b1a34fd075b49345dcfce1318c02639eee84f9
- .tekton/


apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

images:
- name: quay.io/redhat-appstudio/release-service
  newName: quay.io/redhat-appstudio/release-service
  newTag: e9b1a34fd075b49345dcfce1318c02639eee84f9

namespace: release-service

patches:
  - ./manager_resources_patch.yaml
