resources:
- allow-argocd-to-manage.yaml
- argocd-permissions.yaml
- https://github.com/redhat-appstudio/integration-service/config/default?ref=36cde6cf0cf4e16bf54f3a92ba53c5a4df9a9aad

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

images:
- name: quay.io/redhat-appstudio/integration-service
  newName: quay.io/jinqi/integration-service
  newTag: 2023-01-09

namespace: integration-service

patches:
  - ./manager_resources_patch.yaml
